services:
  - type: web
    name: currencyx-backend
    runtime: python
    python:
      version: "3.9"
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: |
      gunicorn main:app \
      --bind 0.0.0.0:$PORT \
      --workers 4 \
      --worker-class uvicorn.workers.UvicornWorker \
      --timeout 120 \
      --log-level info
    envVars:
      - key: API_KEY
        fromGroup: currencyx-env
    healthCheckPath: /api/health