services:
  - type: web
    name: currencyx-fullstack
    runtime: python
    python:
      version: "3.9"
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: |
      python -m uvicorn main:app \
        --bind 0.0.0.0:$PORT \
        --workers 2 \
        --worker-class uvicorn.workers.UvicornWorker \
        --timeout 120 \
        --log-level info
    envVars:
      - key: API_KEY
        fromGroup: currencyx-env
      - key: PORT
        value: 10000
    healthCheckPath: /health
    healthCheckTimeout: 120
    autoDeploy: yes