services:
  - type: web
    name: currencyx-backend
    runtime: python
    python:
      version: "3.9"
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        fromGroup: currencyx-env
    healthCheckPath: /api/health