services:
  - type: web
    name: currencyx-backend
    runtime: python
    python:
      version: "3.9"
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt
<<<<<<< HEAD
    # تم تعديل أمر البدء لاستخدام قيمة PORT التي تحددها منصة Render تلقائياً
    # وإزالة تعريف PORT اليدوي من متغيرات البيئة
    startCommand: |
      gunicorn main:app \
      --bind 0.0.0.0:$PORT \
      --workers 4 \
      --worker-class uvicorn.workers.UvicornWorker \
      --timeout 120 \
      --log-level info
=======
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
>>>>>>> f9dd4ebff42640fb76b34f5483b80a77c67a282d
    envVars:
      - key: API_KEY
        fromGroup: currencyx-env
    healthCheckPath: /api/health