services:
  - type: web
    name: currencyx-backend
    runtime: python
    python:
      version: "3.9"
    buildCommand: |
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_KEY
        fromGroup: currencyx-env
      - key: PORT
        value: 10000
    healthCheckPath: /health
    healthCheckTimeout: 120
    autoDeploy: yes